-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  verify_events

CREATE TABLE IF NOT EXISTS verify_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  type TEXT NOT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  occurred_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT chk_verify_type CHECK (type IN ('verify_success','verify_failure'))
);
